/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf -t 
Author: DemonSammy (https://sketchfab.com/demonsammy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/closet-ddde4fccc5554b24b0c57857ecdaaaaa
Title: Closet
*/

import * as THREE from "three";
import React, { Ref, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import { useColor } from "../store/color";

type GLTFResult = GLTF & {
  nodes: {
    Right_door_closet_text_0: THREE.Mesh;
    Left_door_closet_text_0: THREE.Mesh;
    Top_drawer_closet_text_0: THREE.Mesh;
    Bottom_drawer_closet_text_0: THREE.Mesh;
    Hanger_rod_lambert1_0: THREE.Mesh;
    Closet_Body_closet_text_0: THREE.Mesh;
  };
  materials: {
    closet_text: THREE.MeshStandardMaterial;
    lambert1: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Closets, Closets, Closets, Closets";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>() as Ref<
    THREE.Group<THREE.Object3DEventMap>
  >;

  const model = useColor((state) =>
    state.models.find((model) => model.title === props.name)
  );
  const { nodes, materials, animations } = useGLTF(
    "models/closet/scene.gltf"
  ) as GLTFResult;

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.122}
        >
          <group
            name="2bd011803a3c4c1b8c6ccdb02ebc2bacfbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Closet_Body" position={[-0.041, 11.16, 0]}>
                  <group name="Right_door" position={[4.431, 4.957, -1.942]}>
                    <mesh
                      name="Right_door_closet_text_0"
                      geometry={nodes.Right_door_closet_text_0.geometry}
                      material={
                        new THREE.MeshStandardMaterial({
                          color: model?.formatedColor,
                        })
                      }
                    />
                  </group>
                  <group name="Left_door" position={[-4.483, 4.957, -1.942]}>
                    <mesh
                      name="Left_door_closet_text_0"
                      geometry={nodes.Left_door_closet_text_0.geometry}
                      material={
                        new THREE.MeshStandardMaterial({
                          color: model?.formatedColor,
                        })
                      }
                    />
                  </group>
                  <group name="Top_drawer" position={[-0.033, -3.65, -2.476]}>
                    <mesh
                      name="Top_drawer_closet_text_0"
                      geometry={nodes.Top_drawer_closet_text_0.geometry}
                      material={
                        new THREE.MeshStandardMaterial({
                          color: model?.formatedColor,
                        })
                      }
                    />
                  </group>
                  <group name="Bottom_drawer" position={[-0.03, -4.59, -2.474]}>
                    <mesh
                      name="Bottom_drawer_closet_text_0"
                      geometry={nodes.Bottom_drawer_closet_text_0.geometry}
                      material={
                        new THREE.MeshStandardMaterial({
                          color: model?.formatedColor,
                        })
                      }
                    />
                  </group>
                  <group
                    name="Hanger_rod"
                    position={[0.042, 7.249, 0]}
                    rotation={[0, 0, Math.PI / 2]}
                    scale={[0.182, 2.651, 0.182]}
                  >
                    <mesh
                      name="Hanger_rod_lambert1_0"
                      geometry={nodes.Hanger_rod_lambert1_0.geometry}
                      material={materials.lambert1}
                    />
                  </group>
                  <mesh
                    name="Closet_Body_closet_text_0"
                    geometry={nodes.Closet_Body_closet_text_0.geometry}
                    material={materials.closet_text}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/closet/scene.gltf");
